flaskblog/main/routes.py
from flask import render_template, url_for, redirect, request, Blueprint
from flaskblog.models import Post
from flaskblog.main.forms import RecapSelect

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home", methods=["GET", "POST"])
def home():
    form = RecapSelect()
    if form.validate_on_submit():
        return redirect(url_for('main.recap', category=form.category.data, division=form.division.data))
    posts = Post.query.filter(Post.published==True, Post.post_type!='recap').order_by(Post.date_posted.desc())
    return render_template('home.html', posts=posts, form=form)

@main.route("/unpublished")
def unpublished():
    posts = Post.query.filter_by(published=False).order_by(Post.date_posted.desc())
    return render_template('home.html', posts=posts)

@main.route("/<string:category>")
def category(category):
    posts = Post.query.filter(Post.category==category,Post.published==True, Post.post_type!='recap').order_by(Post.date_posted.desc())
    return render_template('home.html', posts=posts)

@main.route("/recap/", methods=["GET", "POST"])
def all_recap():
    form = RecapSelect()
    if form.validate_on_submit():
        return redirect(url_for('main.recap', category=form.category.data, division=form.division.data))
    posts = Post.query.filter(Post.published==True, Post.post_type=='recap').order_by(Post.week.desc())
    return render_template('recap_home.html', posts=posts, form=form)

@main.route("/recap/<string:category>/<string:division>", methods=["GET", "POST"])
def recap(category, division):
    form = RecapSelect()
    if form.validate_on_submit():
        return redirect(url_for('main.recap', category=form.category.data, division=form.division.data))
    elif request.method == "GET":
        form.category.data = category
        form.division.data = division
    posts = Post.query.filter(Post.published==True, Post.post_type=='recap', Post.category==category).filter(Post.division.contains(division)).order_by(Post.week.desc())
    return render_template('recap_home.html', posts=posts, form=form)

@main.route("/ticker/")
def ticker():
    posts = (
    Post.query.filter(Post.published == True, Post.post_type!='recap').order_by(Post.date_posted.desc()).limit(5))
    return render_template('ticker.html', posts=posts)

flaskblog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post, PostComment
from flaskblog.posts.forms import PostForm, CommentForm, VideoForm, RecapForm
from flaskblog.posts.utils import save_picture, parse_video_url, parse_video_img
from datetime import datetime
from slugify import slugify


posts = Blueprint("posts", __name__)


@posts.route("/post/new", methods=["GET", "POST"])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        # Working on adding Cover Photos
        """if form.picture.data:
            picture_file = save_picture(form.picture.data)
            post.image_file = picture_file"""
        post = Post(
            title=form.title.data,
            category=form.category.data,
            shortdesc=form.shortdesc.data,
            content=form.content.data,
            author=current_user,
            published=False,
            sidebar=True,
            post_type="text",
        )
        # cover_image=post.image_file)
        db.session.add(post)
        db.session.commit()
        post.slug = slugify(form.title.data, max_length=35).lower() + "-" + str(post.id)
        db.session.commit()
        flash("Your comment has been added!", "success")
        return redirect(url_for("posts.postslug", post_slug=post.slug))
    return render_template(
        "create_post.html", title="New Post", form=form, legend="New Post"
    )


@posts.route("/post/<int:post_id>", methods=["GET", "POST"])
def post(post_id):
    post = Post.query.filter_by(id=post_id).first()
    post_id = post.id
    category = post.category
    comments = PostComment.query.filter(PostComment.post_id == post_id).order_by(
        PostComment.date_posted.asc()
    )
    posts = (
        Post.query.filter(
            Post.id != post_id, Post.category == category, Post.published == True
        )
        .order_by(Post.date_posted.desc())
        .limit(6)
    )
    form = CommentForm()
    if form.validate_on_submit():
        comment = PostComment(
            content=form.content.data, user=current_user, post_id=post.id
        )
        db.session.add(comment)
        db.session.commit()
        flash("Your comment has been added!", "success")
        return redirect(
            url_for("posts.postslug", _anchor="commentsection", post_slug=post.slug)
        )

    return render_template(
        "post.html",
        form=form,
        title=post.title,
        shortdesc=post.shortdesc,
        post=post,
        posts=posts,
        comments=comments,
    )


@posts.route("/post/<string:post_slug>", methods=["GET", "POST"])
def postslug(post_slug):
    post = Post.query.filter_by(slug=post_slug).first()
    post_id = post.id
    comments = PostComment.query.filter(PostComment.post_id == post_id).order_by(
        PostComment.date_posted.asc()
    )
    category = post.category
    posts = (
        Post.query.filter(
            Post.id != post_id, Post.category == category, Post.published == True
        )
        .order_by(Post.date_posted.desc())
        .limit(5)
    )
    form = CommentForm()
    if form.validate_on_submit():
        comment = PostComment(
            content=form.content.data, user=current_user, post_id=post.id
        )
        db.session.add(comment)
        db.session.commit()
        flash("Your comment has been added!", "success")
        return redirect(
            url_for("posts.postslug", _anchor="commentsection", post_slug=post.slug)
        )

    if post.post_type == "text":
        return render_template(
            "post.html",
            form=form,
            title=post.title,
            shortdesc=post.shortdesc,
            post=post,
            posts=posts,
            comments=comments,
        )
    elif post.post_type == "video":
        return render_template(
            "video.html",
            form=form,
            title=post.title,
            shortdesc=post.shortdesc,
            post=post,
            posts=posts,
            comments=comments,
        )
    elif post.post_type == "recap":
        return render_template(
            "recap.html",
            form=form,
            title=post.title,
            shortdesc=post.shortdesc,
            post=post,
            posts=posts,
            comments=comments,
        )


@posts.route("/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.category = form.category.data
        post.shortdesc = form.shortdesc.data
        post.content = form.content.data
        db.session.commit()
        flash("Your post has been updated!", "success")
        return redirect(url_for("posts.postslug", post_slug=post.slug))
    elif request.method == "GET":
        form.title.data = post.title
        form.category.data = post.category
        form.shortdesc.data = post.shortdesc
        form.content.data = post.content
    return render_template(
        "create_post.html", title="Update Post", form=form, legend="Update Post"
    )


@posts.route("/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your post has been deleted!", "success")
    return redirect(url_for("main.home"))


@posts.route("/post/<int:post_id>/publish", methods=["POST"])
@login_required
def publish_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        redirect(url_for("posts.post", post_id=post.id))
    post.published = True
    post.date_posted = datetime.utcnow()
    db.session.commit()
    flash("Your post has been Published!", "success")
    return redirect(url_for("posts.postslug", post_slug=post.slug))


@posts.route("/post/<int:post_id>/unpublish", methods=["POST"])
@login_required
def unpublish_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        if current_user.role != "Admin":
            redirect(url_for("posts.postslug", post_slug=post.slug))
    post.published = False
    db.session.commit()
    flash("Your post has been Unpublished!", "success")
    return redirect(url_for("posts.postslug", post_slug=post.slug))


@posts.route("/postcomment/<int:post_id>/<int:comment_id>/delete", methods=["POST"])
@login_required
def delete_comment(comment_id, post_id):
    comment = PostComment.query.get_or_404(comment_id)
    post = Post.query.get_or_404(post_id)
    db.session.delete(comment)
    db.session.commit()
    flash("Comment has been deleted!", "success")
    return redirect(url_for("posts.postslug", post_slug=post.slug))


### VIDEO SECTION ###


@posts.route("/video/new", methods=["GET", "POST"])
@login_required
def new_video():
    form = VideoForm()
    if form.validate_on_submit():
        # Insert logic to parse out video unique identifier to store as video
        videoinput = form.video.data
        post = Post(
            title=form.title.data,
            category=form.category.data,
            shortdesc=form.shortdesc.data,
            content=form.content.data,
            video=form.video.data,
            # post.videotype = form.videotype.data,
            videoimg=parse_video_img(videoinput),
            videourl=parse_video_url(videoinput),
            author=current_user,
            post_type="video",
            published=False,
            sidebar=True,
        )
        db.session.add(post)
        db.session.commit()
        post.slug = slugify(form.title.data, max_length=35).lower() + "-" + str(post.id)
        db.session.commit()
        flash("Your video has been added!", "success")
        return redirect(url_for("posts.postslug", post_slug=post.slug))
    return render_template(
        "create_video.html", title="New Video Post", form=form, legend="New Video Post"
    )


@posts.route("/video/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_video(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    form = VideoForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.category = form.category.data
        post.shortdesc = form.shortdesc.data
        post.video = form.video.data
        videoinput = form.video.data
        post.videoimg = parse_video_img(videoinput)
        post.videourl = parse_video_url(videoinput)
        db.session.commit()
        flash("Your video post has been updated!", "success")
        return redirect(url_for("posts.postslug", post_slug=post.slug))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
        form.category.data = post.category
        form.shortdesc.data = post.shortdesc
        form.video.data = post.video
    return render_template(
        "create_video.html",
        title="Update Video Post",
        form=form,
        legend="Update Video Post",
    )


@posts.route("/recap/new", methods=["GET", "POST"])
@login_required
def new_recap():
    form = RecapForm()
    if form.validate_on_submit():
        videoinput = form.video.data
        title_str = f"{form.category.data} Div {', '.join(form.division.data)} - Week {form.week.data}"
        post = Post(
            title=title_str,
            category=form.category.data,
            content=form.content.data,
            shortdesc=form.shortdesc.data,
            video=form.video.data,
            videoimg=parse_video_img(videoinput),
            videourl=parse_video_url(videoinput),

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(coachname=form.coachname.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(coachname=form.coachname.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.coachname = form.coachname.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.coachname.data = current_user.coachname
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:coachname>")
def user_posts(coachname):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(coachname=coachname).first_or_404()
    posts = Post.query.filter_by(author=user, published=True)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=10)
    return render_template('user_posts.html', posts=posts, user=user)

@users.route("/my_posts")
@login_required
def my_posts():
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(coachname=current_user.coachname).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=10)
    return render_template('my_posts.html', posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(coachname=form.coachname.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
	<p>Content in Progress</p>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
<main role="main" class="container">
	<div class="row">
		{% if post.sidebar != False %}
		<div class="col-md-8 py-2">
			<article class="media content-section">
				{% else %}
				<div class="col-md-12 py-2">
					<article class="media content-section">
						{% endif %}
						<div class="media-body">
							<div class="article-metadata">
								<img class="article-img" style="float:left"
									src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
								<h1 class="article-title" style="margin-bottom: 10px;">{{ post.title }}
									<small class="text-muted">&nbsp;-&nbsp;By&nbsp;<a class="mr-2"
											href="{{ url_for('users.user_posts', coachname=post.author.coachname) }}">{{ post.author.coachname }}</a></small>
								</h1>
								{# {% for role in current_user.role %} #}
								{% if post.author.coachname == current_user.coachname %}
								<div>
									<a class="btn btn-secondary btn-sm mt-1 mb-1"
										href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
									<button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal"
										data-target="#deleteModal">Delete</button>
									{% if post.published == False %}
									<button type="button" class="btn btn-success btn-sm m-1" data-toggle="modal"
										data-target="#publishModal">Publish</button>
									{% elif post.published == True %}
									<button type="button" class="btn btn-secondary btn-sm m-1" data-toggle="modal"
										data-target="#unpublishModal">Unpublish</button>
									{% endif %}
								</div>
								{% endif %}
								{# {% endfor %} #}
							</div>

							<div class="article-content">{{ post.content | safe }}</div>
							<h3> - {{ post.author.coachname }}</h3>
							<p><a class="mr-2" href="{{ url_for('users.user_posts', coachname=post.author.coachname) }}">Read more
									from this writer.</a></p>
						</div>
					</article>
					{% if comments %}
					<article class="media content-section">
						<div class="media-body">
							<a id="commentsection"></a>
							<h4>Comments</h4>
							{% for comment in comments %}
							<p class="card-text text-left">{{ comment.content }} - <a class="mr-2"
									href="{{ url_for('users.user_posts', coachname=comment.user.coachname) }}">{{ comment.user.coachname }}</a>
								{% for role in current_user.role %}
								{% if comment.user.coachname == current_user.coachname %}
								<div class="d-inline btn-group" role="group">
									<button id="btnGroupDrop{{ comment.id }}" type="button"
										class="btn btn-danger dropdown-toggle btn-sm m-1" data-toggle="dropdown" aria-haspopup="true"
										aria-expanded="false">
										Delete Comment
									</button>
									<div class="dropdown-menu" aria-labelledby="btnGroupDrop{{ comment.id }}">
										<form action="{{ url_for('posts.delete_comment', comment_id=comment.id, post_id=post.id) }}"
											method="POST">
											<input class="dropdown-item" type="submit" value="Confirm">
										</form>
									</div>
								</div>
								{% endif %}{% endfor %}</p>


							{% endfor %}
							{% if current_user.is_authenticated %}

							<form method="POST" action="">
								{{ form.hidden_tag() }}
								<fieldset class="form-group">
									<legend class="border-bottom mb-4">{{ legend }}</legend>
									<div class="form-group">
										{{ form.content.label(class="form-control-label") }}
										{% if form.content.errors %}
										{{ form.content(class="form-control form-control-lg is-invalid") }}
										<div class="invalid-feedback">
											{% for error in form.content.errors %}
											<span>{{ error }}</span>
											{% endfor %}
										</div>
										{% else %}
										{{ form.content(class="form-control form-control-lg") }}
										{% endif %}
									</div>
								</fieldset>
								<div class="form-group">
									{{ form.submit(class="btn btn-outline-info") }}
								</div>
							</form>
							{% else %}
							<p></p>
							<p><a class="btn btn-success btn-sm m-1" href="{{ url_for('users.login') }}">Log in to add a comment</a>
							</p>
							{% endif %}

						</div>
					</article>
					{% endif %}
				</div>
				{% if post.sidebar != False %}
				<div class="col-md-4 py-2">

					{% if comments %}
					<div class="card mb-4 shadow-sm d-none d-md-block" style="border-radius: 10px">
						<div class="card-body bg-light" style="border-radius: 10px">
							<a id="commentsection"></a>
							<h4>Comments</h4>
							{% for comment in comments %}
							<p class="card-text">{{ comment.content }} - <a class="mr-2"
									href="{{ url_for('users.user_posts', coachname=comment.user.coachname) }}">{{ comment.user.coachname }}</a>
								{% for role in current_user.role %}
								{% if comment.user.coachname == current_user.coachname %}
								<div class="d-inline btn-group" role="group">
									<button id="btnGroupDrop{{ comment.id }}" type="button"
										class="btn btn-danger dropdown-toggle btn-sm m-1" data-toggle="dropdown" aria-haspopup="true"
										aria-expanded="false">
										Delete Comment
									</button>
									<div class="dropdown-menu" aria-labelledby="btnGroupDrop{{ comment.id }}">
										<form action="{{ url_for('posts.delete_comment', comment_id=comment.id, post_id=post.id) }}"
											method="POST">
											<input class="dropdown-item" type="submit" value="Confirm">
										</form>
									</div>
								</div>

								{% endif %}{% endfor %}</p>


							{% endfor %}
							{% if current_user.is_authenticated %}

							<form method="POST" action="">
								{{ form.hidden_tag() }}
								<fieldset class="form-group">
									<legend class="border-bottom mb-4">{{ legend }}</legend>
									<div class="form-group">
										{{ form.content.label(class="form-control-label") }}
										{% if form.content.errors %}
										{{ form.content(class="form-control form-control-lg is-invalid") }}
										<div class="invalid-feedback">
											{% for error in form.content.errors %}
											<span>{{ error }}</span>
											{% endfor %}
										</div>
										{% else %}
										{{ form.content(class="form-control form-control-lg") }}
										{% endif %}
									</div>
								</fieldset>
								<div class="form-group">
									{{ form.submit(class="btn btn-outline-info") }}
								</div>
							</form>
							{% else %}
							<p></p>
							<p><a class="btn btn-success btn-sm m-1" href="{{ url_for('users.login') }}">Log in to add a comment</a>
							</p>
							{% endif %}

						</div>
					</div>
					{% endif %}

					<div class="card mb-4 shadow-sm" style="border-radius: 10px">
						<div class="card-body bg-light" style="border-radius: 10px">
							<h4>More REBBL Content</h4>

							<p class="card-text text-justify">These links lead to other REBBL related content, information, and
								websites.</p>
							<p>
								<a href="{{ url_for('main.home') }}">Latest News Posts</a><br />
								<a href="https://www.reddit.com/r/ReBBl/" target="_blank">REBBL Reddit Homepage</a><br />
								<a href="https://rebbl.net" target="_blank">REBBL Match Ups and Stats<br />
									<a href="https://nufflytics.com/" target="_blank">Nufflytics - Data Analysis<br />
										<a href="{{ url_for('posts.post', post_id=5) }}">How to Write for REBBL News</a><br />
							</p>

						</div>
					</div>
					{% for post in posts %}
					<div class="card mb-4 shadow-sm" style="border-radius: 10px">
						<div class="card-body bg-light"
							style="background-size: cover;border-top-left-radius: 10px;border-top-right-radius: 10px">
							<h4>
								{% if post.category == 'All' %}<button class="btn btn-dark btn-sm float-right"
									style="border-radius: 10px" href="{{ url_for('main.category', category="All") }}">All</button>
								{% elif post.category == 'GMAN' %}<a href="{{ url_for('main.category', category="GMAN") }}"
									style="border-radius: 10px; background-color:#000e77"
									class="btn btn-secondary btn-sm float-right">GMAN</a>
								{% elif post.category == 'Big O' %}<a href="{{ url_for('main.category', category="Big O") }}"
									style="border-radius: 10px; background-color:#917c06" class="btn btn-secondary btn-sm float-right">Big
									O</a>
								{% elif post.category == 'REL' %}<a href="{{ url_for('main.category', category="REL") }}"
									style="border-radius: 10px; background-color:#7e0000"
									class="btn btn-secondary btn-sm float-right">REL</a>
								{% elif post.category == 'Clan' %}<a href="{{ url_for('main.category', category="Clan") }}"
									style="border-radius: 10px" class="btn btn-secondary btn-sm float-right">Clan</a>
								{% endif %}
								{{ post.title }} </h4>
							<p class="card-text text-justify">{{ post.shortdesc }}</p>
						</div>
						<div class="card-footer text-right">
							<a href="{{ url_for('posts.postslug', post_slug=post.slug) }}"><button type="button"
									class="btn btn-outline-primary btn-sm float-left" style="border-radius: 10px">Read More</button></a>
							By&nbsp;<a class="mr-2"
								href="{{ url_for('users.user_posts', coachname=post.author.coachname) }}">{{ post.author.coachname }}</a>
						</div>
					</div>
					{% endfor %}
				</div>
				{% else %}
				{% for row in posts|batch(3, '&nbsp;') %}
				<div class="row">
					{% for post in row %}
					{% if post != '&nbsp;' %}
					<div class="col-md-4 py-2">
						<div class="card mb-4 shadow-sm  h-100" style="border-radius: 10px">
							<div class="card-body bg-light"
								style="background-size: cover;border-top-left-radius: 10px;border-top-right-radius: 10px">
								<h4>
									{% if post.category == 'All' %}<a class="btn btn-dark btn-sm float-right" style="border-radius: 10px"
										href="{{ url_for('main.category', category="All") }}">All</a>
									{% elif post.category == 'GMAN' %}<a href="{{ url_for('main.category', category="GMAN") }}"
										style="border-radius: 10px; background-color:#000e77"
										class="btn btn-secondary btn-sm float-right">GMAN</a>
									{% elif post.category == 'Big O' %}<a href="{{ url_for('main.category', category="Big O") }}"
										style="border-radius: 10px; background-color:#917c06"
										class="btn btn-secondary btn-sm float-right">Big
										O</a>
									{% elif post.category == 'REL' %}<a href="{{ url_for('main.category', category="REL") }}"
										style="border-radius: 10px; background-color:#7e0000"
										class="btn btn-secondary btn-sm float-right">REL</a>
									{% elif post.category == 'Clan' %}<a href="{{ url_for('main.category', category="Clan") }}"
										style="border-radius: 10px" class="btn btn-secondary btn-sm float-right">Clan</a>
									{% endif %}
									{{ post.title }} </h4>
								<p class="card-text text-justify">{{ post.shortdesc }}</p>
							</div>
							<div class="card-footer text-right">
								<a href="{{ url_for('posts.postslug', post_slug=post.slug) }}"><button type="button"
										class="btn btn-outline-primary btn-sm float-left" style="border-radius: 10px">Read More</button></a>
								By&nbsp;<a class="mr-2"
									href="{{ url_for('users.user_posts', coachname=post.author.coachname) }}">{{ post.author.coachname }}</a>
							</div>
						</div>
					</div>
					{% endif %}
					{% endfor %}
				</div>
				{% endfor %}
				{% endif %}
		</div>
</main>
<!-- Delete Post -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
	aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
					<input class="btn btn-danger" type="submit" value="Delete">
				</form>
			</div>
		</div>
	</div>
</div>

<!-- Publish Post -->
<div class="modal fade" id="publishModal" tabindex="-1" role="dialog" aria-labelledby="publishModalLabel"
	aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="publishModalLabel">Publish Post?</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<form action="{{ url_for('posts.publish_post', post_id=post.id) }}" method="POST">
					<input class="btn btn-success" type="submit" value="Publish">
				</form>
			</div>
		</div>
	</div>
</div>

<!-- Unpublish Post -->
<div class="modal fade" id="unpublishModal" tabindex="-1" role="dialog" aria-labelledby="unpublishModalLabel"
	aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="unpublishModal">Unpublish Post?</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<form action="{{ url_for('posts.unpublish_post', post_id=post.id) }}" method="POST">
					<input class="btn btn-success" type="submit" value="Unpublish">
				</form>
			</div>
		</div>
	</div>
</div>



{% endblock content %}